apiVersion: 1

datasources:
  - name: NetSentinel-PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      database: netsentinel
      sslmode: disable
      postgresVersion: 15
      timescaledb: false
